
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/663291fc1569183fda25118a
###
GET http://localhost:3000/contacts/663298128c4f5ef1e4c4e8ae
###
GET http://localhost:3000/contacts/663298128c4f5ef1e4c4e8af
###
GET https://cse341-ezpk.onrender.com/contacts
###
GET https://cse341-ezpk.onrender.com/contacts/663298128c4f5ef1e4c4e8ad
###
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Tammy",
  "lastName": "Green",
  "email": "tammyg@gmail.com",
  "favoriteColor": "green",
  "birthday": "03/25/1988"
}

###
PUT http://localhost:3000/contacts/663bf2a4700321c607f353be
Content-Type: application/json

{
  "firstName": "Tammy",
  "lastName": "Green",
  "email": "tammyg@gmail.com",
  "favoriteColor": "Yellow",
  "birthday": "03/25/1988"
}
###
DELETE http://localhost:3000/contacts/663bf2a4700321c607f353be